server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: User-Service
        uri: lb://User-Service
        predicates:
        - Path=/user/**
      - id: Department-Service
        uri: lb://Department-Service
        predicates:
        - Path=/department/**
